# robustness_table.py
# re-estimates the full model under UPC, store, and two-way (CGM) clustering
# exports robustness_table.tex

import pandas as pd
import numpy as np
import statsmodels.api as sm
import warnings
warnings.filterwarnings("ignore")
import os

ROOT = os.path.dirname(os.path.abspath(__file__))

print("Loading data...")
df = pd.read_csv(os.path.join(ROOT, "scratch", "detergent_clean.csv"))
df["log_size"] = np.log(df["size_oz"])

# design matrix (same as model 4 in regressions.py)
store_dummies = pd.get_dummies(df["STORE"], prefix="store", drop_first=True).astype(float)
brand_dummies = pd.get_dummies(df["brand"],  prefix="brand",  drop_first=True).astype(float)

y = df["ppu_cents"].values
X = pd.concat([
    pd.Series(1.0, index=df.index, name="const"),
    df[["log_size", "sale_flag"]],
    store_dummies,
    brand_dummies,
], axis=1).fillna(0)

cols = list(X.columns)
print(f"N = {len(y):,}, k = {len(cols)}")

print("Fitting OLS...")
model = sm.OLS(y, X.values).fit()

# three clustering schemes
print("UPC-clustered SEs...")
res_upc = model.get_robustcov_results(cov_type="cluster", groups=df["UPC"].values)

print("Store-clustered SEs...")
res_store = model.get_robustcov_results(cov_type="cluster", groups=df["STORE"].values)

print("Two-way clustered SEs (CGM)...")
upc_store = (df["UPC"].astype(str) + "_" + df["STORE"].astype(str)).values
res_inter = model.get_robustcov_results(cov_type="cluster", groups=upc_store)

# CGM formula: V_two = V_upc + V_store - V_intersection
V_upc   = np.array(res_upc.cov_params())
V_store = np.array(res_store.cov_params())
V_inter = np.array(res_inter.cov_params())
V_two   = V_upc + V_store - V_inter
se_two  = np.sqrt(np.abs(np.diag(V_two)))

# pull out the coefficients we care about
idx_ls = cols.index("log_size")
idx_sf = cols.index("sale_flag")
coef_ls = model.params[idx_ls]
coef_sf = model.params[idx_sf]


def fmt(coef, se, digits=3):
    t = abs(coef / se) if se > 0 else 0
    stars = "***" if t > 2.576 else ("**" if t > 1.96 else ("*" if t > 1.645 else ""))
    return f"{coef:.{digits}f}{stars}", f"({se:.{digits}f})"


c1_ls, s1_ls = fmt(coef_ls, res_upc.bse[idx_ls])
c2_ls, s2_ls = fmt(coef_ls, res_store.bse[idx_ls])
c3_ls, s3_ls = fmt(coef_ls, se_two[idx_ls])

c1_sf, s1_sf = fmt(coef_sf, res_upc.bse[idx_sf])
c2_sf, s2_sf = fmt(coef_sf, res_store.bse[idx_sf])
c3_sf, s3_sf = fmt(coef_sf, se_two[idx_sf])

r2 = f"{model.rsquared:.3f}"
n_obs = f"{int(model.nobs):,}"

print(f"\nlog_size: {c1_ls} {s1_ls} | {c2_ls} {s2_ls} | {c3_ls} {s3_ls}")
print(f"sale_flag: {c1_sf} {s1_sf} | {c2_sf} {s2_sf} | {c3_sf} {s3_sf}")

# write latex table
latex = r"""% generated by robustness_table.py
\begin{table}[H]
\centering
\caption{Robustness Checks: Alternative Clustering Schemes (Full Model)}
\label{tab:robustness}
\begin{tabular}{lccc}
\toprule
 & (1) & (2) & (3) \\
 & UPC Clustered & Store Clustered & Two-Way Clustered \\
 & & & (UPC $\times$ Store) \\
\midrule
""" + r"$\ln(\text{Size})$" + f" & {c1_ls} & {c2_ls} & {c3_ls} \\\\\n" + \
f" & {s1_ls} & {s2_ls} & {s3_ls} \\\\[4pt]\n" + \
r"Sale indicator" + f" & {c1_sf} & {c2_sf} & {c3_sf} \\\\\n" + \
f" & {s1_sf} & {s2_sf} & {s3_sf} \\\\[4pt]\n" + r"""\midrule
Store FE    & \checkmark & \checkmark & \checkmark \\
Brand FE    & \checkmark & \checkmark & \checkmark \\
$R^{2}$     & """ + r2 + " & " + r2 + " & " + r2 + r""" \\
$N$         & \multicolumn{3}{c}{""" + n_obs + r"""} \\
\bottomrule
\multicolumn{4}{p{0.88\textwidth}}{\footnotesize \textit{Notes:}
Dependent variable: per-unit price (cents/oz). All three columns use
the same OLS regression with store and brand fixed effects; only the
covariance estimator differs. Cluster-robust standard errors in
parentheses. Column~(3) applies the Cameron, Gelbach, and Miller
(2011) two-way formula:
$\hat{V}_{\text{two-way}} =
 \hat{V}_{\text{UPC}} + \hat{V}_{\text{Store}}
 - \hat{V}_{\text{UPC}\times\text{Store}}$.
Point estimates are identical across columns.
$^{***}p<0.01$, $^{**}p<0.05$, $^{*}p<0.10$.}
\end{tabular}
\end{table}
"""

out_path = os.path.join(ROOT, "robustness_table.tex")
with open(out_path, "w") as f:
    f.write(latex)
print(f"\nWrote {out_path}")
